# Generated by Django 5.0.2 on 2024-02-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_arearecord_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arearecord',
            name='month',
            field=models.CharField(choices=[('Jan', 'jan'), ('Feb', 'feb'), ('Mar', 'mar'), ('Apr', 'apr'), ('May', 'may'), ('Jun', 'jun'), ('Jul', 'jul'), ('Aug', 'aug'), ('Sep', 'sep'), ('Oct', 'oct'), ('Nov', 'nov'), ('Dec', 'dec')], max_length=4),
        ),
    ]
